### ISSUE TITLE
Storybook builds are broken

### ISSUE THREAD

**Issue by efoken** [atomicojs/storybook#7]
The `sb dev` works, but our `sb build` is broken now that we migrated Webpack to Vite. We're getting these errors:

```base
file: /Users/.../node_modules/@atomico/storybook/lib/core.js:2:0
1: import { options } from './options.js';
2: import '@storybook/addons';
   ^
3: import '@storybook/docs-tools';
4: import 'atomico';
ERR! RollupError: Unexpected token
```

I created a patch that removed all 3 import lines – they seem to be superflous, and also I was looking at `core.ts`, there are no imports, where are they coming from?

I removed lines 2-4 and afterwards `sb build` seems to work again.

The Storybook `main.ts` that we are using:

```ts
const config: StorybookConfig = {
  stories: [{ directory: '../packages/html/src' }],
  staticDirs: ['./public', { from: '../packages/fonts', to: '/fonts' }],
  addons: [
    '@storybook/addon-a11y',
    '@storybook/addon-essentials',
  ],
  framework: '@storybook/web-components-vite',
  docs: {
    autodocs: 'tag',
  },
  viteFinal: (config) =>
    mergeConfig(config, {
      plugins: atomico({
        cssLiterals: {
          postcss: true,
        },
      }),
    }),
};
```

And of course we have the decorator in `preview.ts`.

Setup:

- Node.js 18.16.1
- Yarn v1
- Storybook 7.2.1

**Comment by efoken** [comment]
The patch needed to fix this:

```
diff --git a/node_modules/@atomico/storybook/lib/core.js b/node_modules/@atomico/storybook/lib/core.js
index cce3cc3..2306b83 100644
--- a/node_modules/@atomico/storybook/lib/core.js
+++ b/node_modules/@atomico/storybook/lib/core.js
@@ -1,8 +1,5 @@
 import { options } from './options.js';
 export { decorator } from './decorator.js';
-import '@storybook/addons';
-import '@storybook/docs-tools';
-import 'atomico';
 
 const getAutoControl = (prop, type) => options.match.find(
   ({ regExp, and }) => regExp.test(prop) ? and ? type === and : true : false
```

**Comment by UpperCod** [comment]
Hi, thanks for sharing your issue, with what configuration are you running this pkg?

1. window ?
2. node 20.* ?
3. npm 9.* ?
4. Yarn?

**Comment by UpperCod** [comment]
I have managed to replicate the error, I am looking for a solution in the compilation process... working to fix it

**Comment by efoken** [comment]
Wow nice, thank you, seems to work with the newest `@atomico/vite` version 🙏

**Comment by UpperCod** [comment]
Ready @efoken is fixed 🎉
